### PR TITLE
Components

### PR DESCRIPTION
**Pull request by Meltrust**
### In this project I:

- Followed the tutorial step by step, up to "Adding styles"
- Created a setup for React by using the instructions (CRA).
- Displayed the main results, in a practical and easy to view way.
- Delivered the project with an organized folder structure.
- Set up code linters.
- Served project with Webpack, as required.
- Added some branding "todix-react"
- Deployed to gh-pages.

Thanks for the review!! :smiley:

### CODE REVIEW

**Comment by mustabbas** [comment]
- [x] The Readme file should have a live demo please add that

**Comment by mustabbas** [comment]
- [x] Linter is not set up correctly for this repository. please check Linter

**Comment by mustabbas** [comment]
- [x] Edit to do list not working

**Review by mustabbas — CHANGES_REQUESTED** [review]
Hi @Meltrust 
Good job so far! Your code looks fine, good job 👍 👍
There are some issues that you still need to work on to go to the next project but you are almost there!

### To highlight:
Gitflow is used 👏
Good PR description 👏
### Required Changes ♻️
 Check inline comments for more information ⏬
### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the Code reviews limits policy [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/restricted?return_to=https%3A%2F%2Fmicroverse.zendesk.com%2Fhc%2Fen-us%2Farticles%2F1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by Meltrust** [comment]
Done :)

**Comment by Meltrust** [comment]
# Corrected requested issues:

- Add live demo
- Add and fix linters
- Correct edit functionality

Thanks!!!

**Review by mustabbas — APPROVED** [review]
### Status: Approve 🥇 ✔
Hi @Meltrust ,
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Pull request merged**
